/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.1
processor: MKV11Z64xxx7
package_id: MKV11Z64VFM7
mcu_data: ksdk2_0
processor_version: 4.0.0
pin_labels:
- {pin_num: '3', pin_signal: ADC0_SE1/ADC0_DP1/ADC1_SE0/PTE16/SPI0_PCS0/UART1_TX/FTM_CLKIN0/FTM0_FLT3, label: TP2, identifier: TP2}
- {pin_num: '4', pin_signal: ADC0_DM1/ADC0_SE5/ADC1_SE5/PTE17/LLWU_P19/SPI0_SCK/UART1_RX/FTM_CLKIN1/LPTMR0_ALT3, label: TP3, identifier: TP3}
- {pin_num: '5', pin_signal: ADC0_SE6/ADC1_SE1/ADC1_DP1/PTE18/LLWU_P20/SPI0_SOUT/UART1_CTS_b/I2C0_SDA/SPI0_SIN, label: SDA, identifier: SDA}
- {pin_num: '6', pin_signal: ADC0_SE7/ADC1_SE7/ADC1_DM1/PTE19/SPI0_SIN/UART1_RTS_b/I2C0_SCL/SPI0_SOUT, label: SCL, identifier: SCL}
- {pin_num: '9', pin_signal: ADC1_SE4/CMP1_IN4/DAC0_OUT/PTE30/FTM0_CH3/FTM_CLKIN1, label: CH1_DIM, identifier: CH1_DIM}
- {pin_num: '10', pin_signal: PTE24/CAN0_TX/FTM0_CH0/I2C0_SCL/EWM_OUT_b, label: CH2_DIM, identifier: CH2_DIM}
- {pin_num: '11', pin_signal: PTE25/LLWU_P21/CAN0_RX/FTM0_CH1/I2C0_SDA/EWM_IN, label: CH3_DIM, identifier: CH3_DIM}
- {pin_num: '12', pin_signal: PTA0/UART0_CTS_b/FTM0_CH5/EWM_IN/SWD_CLK, label: SWD_CLK, identifier: SWD_CLK}
- {pin_num: '13', pin_signal: PTA1/UART0_RX/FTM2_CH0/CMP0_OUT/FTM2_QD_PHA/FTM1_CH1/FTM4_CH0, label: CH4_DIM, identifier: CH4_DIM}
- {pin_num: '14', pin_signal: PTA2/UART0_TX/FTM2_CH1/CMP1_OUT/FTM2_QD_PHB/FTM1_CH0/FTM4_CH1, label: CH5_DIM, identifier: CH5_DIM}
- {pin_num: '15', pin_signal: PTA3/UART0_RTS_b/FTM0_CH0/FTM2_FLT0/EWM_OUT_b/SWD_DIO, label: SWD_DIO, identifier: SWD_DIO}
- {pin_num: '16', pin_signal: PTA4/LLWU_P3/FTM0_CH1/FTM4_FLT0/FTM0_FLT3/NMI_b, label: OPEN, identifier: OPEN}
- {pin_num: '17', pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0/FTM3_CH2, label: EXTAL, identifier: EXTAL}
- {pin_num: '18', pin_signal: XTAL0/PTA19/FTM0_FLT0/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1, label: XTAL, identifier: XTAL}
- {pin_num: '19', pin_signal: PTA20/RESET_b, label: RESET, identifier: RESET}
- {pin_num: '20', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA/UART0_RX, label: CH6_DIM, identifier: CH6_DIM}
- {pin_num: '21', pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM0_FLT2/EWM_IN/FTM1_QD_PHB/UART0_TX, label: CH7_DIM, identifier: CH7_DIM}
- {pin_num: '23', pin_signal: ADC0_SE11/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FTM2_CH1, label: TP7, identifier: TP7}
- {pin_num: '25', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/CMP1_OUT, label: TP6, identifier: TP6}
- {pin_num: '26', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT/FTM0_CH2, label: TP5, identifier: TP5}
- {pin_num: '27', pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB_EXTRG1/UART0_RX/I2C0_SCL, label: UART_RX, identifier: UART_RX}
- {pin_num: '28', pin_signal: CMP0_IN1/PTC7/SPI0_SIN/UART0_TX/I2C0_SDA, label: UART_TX, identifier: UART_TX}
- {pin_num: '22', pin_signal: ADC1_SE3/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FTM2_CH0, label: TP9, identifier: TP9}
- {pin_num: '24', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/FTM3_FLT0, label: CH8_DIM, identifier: CH8_DIM}
- {pin_num: '29', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FTM2_CH0/EWM_IN/SPI0_PCS0, label: CH9_DIM, identifier: CH9_DIM}
- {pin_num: '30', pin_signal: ADC0_SE3/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/FTM2_CH1/EWM_OUT_b/SPI0_SCK, label: CH10_DIM, identifier: CH10_DIM}
- {pin_num: '31', pin_signal: ADC1_SE6/PTD6/LLWU_P15/FTM4_CH0/UART0_RX/FTM0_CH0/FTM1_CH0/FTM0_FLT0/SPI0_SOUT, label: CH11_DIM, identifier: CH11_DIM}
- {pin_num: '32', pin_signal: PTD7/FTM4_CH1/UART0_TX/FTM0_CH1/FTM1_CH1/FTM0_FLT1/SPI0_SIN, label: CH12_DIM, identifier: CH12_DIM}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: GPIOE, signal: 'GPIO, 16', pin_signal: ADC0_SE1/ADC0_DP1/ADC1_SE0/PTE16/SPI0_PCS0/UART1_TX/FTM_CLKIN0/FTM0_FLT3, slew_rate: fast}
  - {pin_num: '4', peripheral: GPIOE, signal: 'GPIO, 17', pin_signal: ADC0_DM1/ADC0_SE5/ADC1_SE5/PTE17/LLWU_P19/SPI0_SCK/UART1_RX/FTM_CLKIN1/LPTMR0_ALT3, slew_rate: fast}
  - {pin_num: '5', peripheral: I2C0, signal: SDA, pin_signal: ADC0_SE6/ADC1_SE1/ADC1_DP1/PTE18/LLWU_P20/SPI0_SOUT/UART1_CTS_b/I2C0_SDA/SPI0_SIN, slew_rate: fast}
  - {pin_num: '6', peripheral: I2C0, signal: SCL, pin_signal: ADC0_SE7/ADC1_SE7/ADC1_DM1/PTE19/SPI0_SIN/UART1_RTS_b/I2C0_SCL/SPI0_SOUT}
  - {pin_num: '12', peripheral: SWD, signal: CLK, pin_signal: PTA0/UART0_CTS_b/FTM0_CH5/EWM_IN/SWD_CLK}
  - {pin_num: '15', peripheral: SWD, signal: DIO, pin_signal: PTA3/UART0_RTS_b/FTM0_CH0/FTM2_FLT0/EWM_OUT_b/SWD_DIO}
  - {pin_num: '16', peripheral: GPIOA, signal: 'GPIO, 4', pin_signal: PTA4/LLWU_P3/FTM0_CH1/FTM4_FLT0/FTM0_FLT3/NMI_b, direction: OUTPUT}
  - {pin_num: '17', peripheral: OSC0, signal: EXTAL0, pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0/FTM3_CH2}
  - {pin_num: '18', peripheral: OSC0, signal: XTAL0, pin_signal: XTAL0/PTA19/FTM0_FLT0/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1}
  - {pin_num: '19', peripheral: LLWU, signal: RESET, pin_signal: PTA20/RESET_b}
  - {pin_num: '23', peripheral: GPIOC, signal: 'GPIO, 2', pin_signal: ADC0_SE11/CMP1_IN0/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FTM2_CH1, direction: OUTPUT}
  - {pin_num: '25', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/CMP1_OUT, direction: OUTPUT}
  - {pin_num: '26', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT/FTM0_CH2, direction: OUTPUT}
  - {pin_num: '27', peripheral: UART0, signal: RX, pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_SOUT/PDB_EXTRG1/UART0_RX/I2C0_SCL}
  - {pin_num: '28', peripheral: UART0, signal: TX, pin_signal: CMP0_IN1/PTC7/SPI0_SIN/UART0_TX/I2C0_SDA, direction: OUTPUT}
  - {pin_num: '20', peripheral: FTM1, signal: 'CH, 0', pin_signal: ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA/UART0_RX, direction: OUTPUT}
  - {pin_num: '22', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: ADC1_SE3/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FTM2_CH0, direction: OUTPUT}
  - {pin_num: '10', peripheral: FTM0, signal: 'CH, 0', pin_signal: PTE24/CAN0_TX/FTM0_CH0/I2C0_SCL/EWM_OUT_b, direction: OUTPUT}
  - {pin_num: '11', peripheral: FTM0, signal: 'CH, 1', pin_signal: PTE25/LLWU_P21/CAN0_RX/FTM0_CH1/I2C0_SDA/EWM_IN, direction: OUTPUT}
  - {pin_num: '13', peripheral: FTM2, signal: 'CH, 0', pin_signal: PTA1/UART0_RX/FTM2_CH0/CMP0_OUT/FTM2_QD_PHA/FTM1_CH1/FTM4_CH0, direction: OUTPUT}
  - {pin_num: '14', peripheral: FTM2, signal: 'CH, 1', pin_signal: PTA2/UART0_TX/FTM2_CH1/CMP1_OUT/FTM2_QD_PHB/FTM1_CH0/FTM4_CH1, direction: OUTPUT}
  - {pin_num: '21', peripheral: FTM1, signal: 'CH, 1', pin_signal: ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM0_FLT2/EWM_IN/FTM1_QD_PHB/UART0_TX}
  - {pin_num: '24', peripheral: FTM0, signal: 'CH, 2', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/FTM3_FLT0, direction: OUTPUT}
  - {pin_num: '29', peripheral: FTM0, signal: 'CH, 4', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FTM2_CH0/EWM_IN/SPI0_PCS0, direction: OUTPUT}
  - {pin_num: '30', peripheral: FTM0, signal: 'CH, 5', pin_signal: ADC0_SE3/PTD5/SPI0_PCS2/UART0_CTS_b/FTM0_CH5/FTM2_CH1/EWM_OUT_b/SPI0_SCK, direction: OUTPUT}
  - {pin_num: '31', peripheral: FTM4, signal: 'CH, 0', pin_signal: ADC1_SE6/PTD6/LLWU_P15/FTM4_CH0/UART0_RX/FTM0_CH0/FTM1_CH0/FTM0_FLT0/SPI0_SOUT, direction: OUTPUT}
  - {pin_num: '32', peripheral: FTM4, signal: 'CH, 1', pin_signal: PTD7/FTM4_CH1/UART0_TX/FTM0_CH1/FTM1_CH1/FTM0_FLT1/SPI0_SIN, direction: OUTPUT}
  - {pin_num: '9', peripheral: FTM0, signal: 'CH, 3', pin_signal: ADC1_SE4/CMP1_IN4/DAC0_OUT/PTE30/FTM0_CH3/FTM_CLKIN1, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t OPEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA4 (pin 16)  */
    GPIO_PinInit(BOARD_INITPINS_OPEN_GPIO, BOARD_INITPINS_OPEN_PIN, &OPEN_config);

    gpio_pin_config_t TP9_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin 22)  */
    GPIO_PinInit(BOARD_INITPINS_TP9_GPIO, BOARD_INITPINS_TP9_PIN, &TP9_config);

    gpio_pin_config_t TP7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC2 (pin 23)  */
    GPIO_PinInit(BOARD_INITPINS_TP7_GPIO, BOARD_INITPINS_TP7_PIN, &TP7_config);

    gpio_pin_config_t TP6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin 25)  */
    GPIO_PinInit(BOARD_INITPINS_TP6_GPIO, BOARD_INITPINS_TP6_PIN, &TP6_config);

    gpio_pin_config_t TP5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC5 (pin 26)  */
    GPIO_PinInit(BOARD_INITPINS_TP5_GPIO, BOARD_INITPINS_TP5_PIN, &TP5_config);

    /* PORTA0 (pin 12) is configured as SWD_CLK */
    PORT_SetPinMux(BOARD_INITPINS_SWD_CLK_PORT, BOARD_INITPINS_SWD_CLK_PIN, kPORT_MuxAlt7);

    /* PORTA1 (pin 13) is configured as FTM2_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_CH4_DIM_PORT, BOARD_INITPINS_CH4_DIM_PIN, kPORT_MuxAlt3);

    /* PORTA18 (pin 17) is configured as EXTAL0 */
    PORT_SetPinMux(BOARD_INITPINS_EXTAL_PORT, BOARD_INITPINS_EXTAL_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTA19 (pin 18) is configured as XTAL0 */
    PORT_SetPinMux(BOARD_INITPINS_XTAL_PORT, BOARD_INITPINS_XTAL_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTA2 (pin 14) is configured as FTM2_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_CH5_DIM_PORT, BOARD_INITPINS_CH5_DIM_PIN, kPORT_MuxAlt3);

    /* PORTA20 (pin 19) is configured as RESET_b */
    PORT_SetPinMux(BOARD_INITPINS_RESET_PORT, BOARD_INITPINS_RESET_PIN, kPORT_MuxAlt7);

    /* PORTA3 (pin 15) is configured as SWD_DIO */
    PORT_SetPinMux(BOARD_INITPINS_SWD_DIO_PORT, BOARD_INITPINS_SWD_DIO_PIN, kPORT_MuxAlt7);

    /* PORTA4 (pin 16) is configured as PTA4 */
    PORT_SetPinMux(BOARD_INITPINS_OPEN_PORT, BOARD_INITPINS_OPEN_PIN, kPORT_MuxAsGpio);

    /* PORTB0 (pin 20) is configured as FTM1_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_CH6_DIM_PORT, BOARD_INITPINS_CH6_DIM_PIN, kPORT_MuxAlt3);

    /* PORTB1 (pin 21) is configured as FTM1_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_CH7_DIM_PORT, BOARD_INITPINS_CH7_DIM_PIN, kPORT_MuxAlt3);

    /* PORTC1 (pin 22) is configured as PTC1 */
    PORT_SetPinMux(BOARD_INITPINS_TP9_PORT, BOARD_INITPINS_TP9_PIN, kPORT_MuxAsGpio);

    /* PORTC2 (pin 23) is configured as PTC2 */
    PORT_SetPinMux(BOARD_INITPINS_TP7_PORT, BOARD_INITPINS_TP7_PIN, kPORT_MuxAsGpio);

    /* PORTC3 (pin 24) is configured as FTM0_CH2 */
    PORT_SetPinMux(BOARD_INITPINS_CH8_DIM_PORT, BOARD_INITPINS_CH8_DIM_PIN, kPORT_MuxAlt4);

    /* PORTC4 (pin 25) is configured as PTC4 */
    PORT_SetPinMux(BOARD_INITPINS_TP6_PORT, BOARD_INITPINS_TP6_PIN, kPORT_MuxAsGpio);

    /* PORTC5 (pin 26) is configured as PTC5 */
    PORT_SetPinMux(BOARD_INITPINS_TP5_PORT, BOARD_INITPINS_TP5_PIN, kPORT_MuxAsGpio);

    /* PORTC6 (pin 27) is configured as UART0_RX */
    PORT_SetPinMux(BOARD_INITPINS_UART_RX_PORT, BOARD_INITPINS_UART_RX_PIN, kPORT_MuxAlt5);

    /* PORTC7 (pin 28) is configured as UART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_UART_TX_PORT, BOARD_INITPINS_UART_TX_PIN, kPORT_MuxAlt5);

    /* PORTD4 (pin 29) is configured as FTM0_CH4 */
    PORT_SetPinMux(BOARD_INITPINS_CH9_DIM_PORT, BOARD_INITPINS_CH9_DIM_PIN, kPORT_MuxAlt4);

    /* PORTD5 (pin 30) is configured as FTM0_CH5 */
    PORT_SetPinMux(BOARD_INITPINS_CH10_DIM_PORT, BOARD_INITPINS_CH10_DIM_PIN, kPORT_MuxAlt4);

    /* PORTD6 (pin 31) is configured as FTM4_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_CH11_DIM_PORT, BOARD_INITPINS_CH11_DIM_PIN, kPORT_MuxAlt2);

    /* PORTD7 (pin 32) is configured as FTM4_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_CH12_DIM_PORT, BOARD_INITPINS_CH12_DIM_PIN, kPORT_MuxAlt2);

    /* PORTE16 (pin 3) is configured as PTE16 */
    PORT_SetPinMux(BOARD_INITPINS_TP2_PORT, BOARD_INITPINS_TP2_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[16] = ((PORTE->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                      /* Slew Rate Enable: Fast slew rate is configured on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_SRE(kPORT_FastSlewRate));

    /* PORTE17 (pin 4) is configured as PTE17 */
    PORT_SetPinMux(BOARD_INITPINS_TP3_PORT, BOARD_INITPINS_TP3_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[17] = ((PORTE->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                      /* Slew Rate Enable: Fast slew rate is configured on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_SRE(kPORT_FastSlewRate));

    /* PORTE18 (pin 5) is configured as I2C0_SDA */
    PORT_SetPinMux(BOARD_INITPINS_SDA_PORT, BOARD_INITPINS_SDA_PIN, kPORT_MuxAlt4);

    PORTE->PCR[18] = ((PORTE->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                      /* Slew Rate Enable: Fast slew rate is configured on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_SRE(kPORT_FastSlewRate));

    /* PORTE19 (pin 6) is configured as I2C0_SCL */
    PORT_SetPinMux(BOARD_INITPINS_SCL_PORT, BOARD_INITPINS_SCL_PIN, kPORT_MuxAlt4);

    /* PORTE24 (pin 10) is configured as FTM0_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_CH2_DIM_PORT, BOARD_INITPINS_CH2_DIM_PIN, kPORT_MuxAlt3);

    /* PORTE25 (pin 11) is configured as FTM0_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_CH3_DIM_PORT, BOARD_INITPINS_CH3_DIM_PIN, kPORT_MuxAlt3);

    /* PORTE30 (pin 9) is configured as FTM0_CH3 */
    PORT_SetPinMux(BOARD_INITPINS_CH1_DIM_PORT, BOARD_INITPINS_CH1_DIM_PIN, kPORT_MuxAlt3);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK | SIM_SOPT5_UART0RXSRC_MASK)))

                  /* UART 0 Transmit Data Source Select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX)

                  /* UART 0 Receive Data Source Select: UART0_RX pin. */
                  | SIM_SOPT5_UART0RXSRC(SOPT5_UART0RXSRC_UART_RX));

    SIM->SOPT8 =
        ((SIM->SOPT8 &
          /* Mask bits to zero which are setting */
          (~(SIM_SOPT8_FTM0OCH0SRC_MASK | SIM_SOPT8_FTM0OCH1SRC_MASK | SIM_SOPT8_FTM0OCH2SRC_MASK | SIM_SOPT8_FTM0OCH3SRC_MASK | SIM_SOPT8_FTM0OCH4SRC_MASK | SIM_SOPT8_FTM0OCH5SRC_MASK | SIM_SOPT8_FTM2OCH0SRC_MASK | SIM_SOPT8_FTM2OCH1SRC_MASK)))

         /* FTM0 channel 0 output PWM/OCMP mode source select: FTM0CH0 pin is the output of FTM0 channel 0
          * PWM/OCMP. */
         | SIM_SOPT8_FTM0OCH0SRC(SOPT8_FTM0OCH0SRC_NO_MODULATION)

         /* FTM0 channel 1 output PWM/OCMP mode source select: FTM0CH1 pin is the output of FTM0 channel 1
          * PWM/OCMP. */
         | SIM_SOPT8_FTM0OCH1SRC(SOPT8_FTM0OCH1SRC_NO_MODULATION)

         /* FTM0 channel 2 output PWM/OCMP mode source select: FTM0CH2 pin is the output of FTM0 channel 2
          * PWM/OCMP. */
         | SIM_SOPT8_FTM0OCH2SRC(SOPT8_FTM0OCH2SRC_NO_MODULATION)

         /* FTM0 channel 3 output PWM/OCMP mode source select: FTM0CH3 pin is the output of FTM0 channel 3
          * PWM/OCMP. */
         | SIM_SOPT8_FTM0OCH3SRC(SOPT8_FTM0OCH3SRC_NO_MODULATION)

         /* FTM0 channel 4 output PWM/OCMP mode source select: FTM0CH4 pin is the output of FTM0 channel 4
          * PWM/OCMP. */
         | SIM_SOPT8_FTM0OCH4SRC(SOPT8_FTM0OCH4SRC_NO_MODULATION)

         /* FTM0 channel 5 output PWM/OCMP mode source select: FTM0CH5 pin is the output of FTM0 channel 5
          * PWM/OCMP. */
         | SIM_SOPT8_FTM0OCH5SRC(SOPT8_FTM0OCH5SRC_NO_MODULATION)

         /* FTM2 channel 0 output PWM/OCMP mode source select: FTM2CH0 pin is the output of FTM2 channel 0
          * PWM/OCMP. */
         | SIM_SOPT8_FTM2OCH0SRC(SOPT8_FTM2OCH0SRC_NO_MODULATION)

         /* FTM2 channel 1 output PWM/OCMP mode source select: FTM2CH1 pin is the output of FTM2 channel 1
          * PWM/OCMP. */
         | SIM_SOPT8_FTM2OCH1SRC(SOPT8_FTM2OCH1SRC_NO_MODULATION));

    SIM->SOPT9 = ((SIM->SOPT9 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT9_FTM4OCH0SRC_MASK | SIM_SOPT9_FTM4OCH1SRC_MASK)))

                  /* FTM4 channel 0 output PWM/OCMP mode source select: FTM4CH0 pin is the output of FTM4 channel
                   * 0 PWM/OCMP. */
                  | SIM_SOPT9_FTM4OCH0SRC(SOPT9_FTM4OCH0SRC_NO_MODULATION)

                  /* FTM4 channel 1 output PWM/OCMP mode source select: FTM4CH1 pin is the output of FTM4 channel
                   * 1 PWM/OCMP. */
                  | SIM_SOPT9_FTM4OCH1SRC(SOPT9_FTM4OCH1SRC_NO_MODULATION));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
